<?php
/* This file was automatically generated by the `grunt libs:cachebuster` command (Thu May 26 2022 22:28:12 GMT+0200 (Central European Summer Time)). */
return array(
	'src/public/dist/admin.js' => '81f921075a1533693c4d3ba9c4ad35ec',
	'src/public/dist/interfaces.js' => '53f73b48eaeb47fb020c3ce9aa8ce945',
	'src/public/dist/vendor-admin.js' => 'f9cad65b727c4d56b88f04ddd379e23c',
	'src/public/dist/vendor-widget.js' => '8b27e3fa4663775ccfb22e4109fdb2c5',
	'src/public/dist/widget.js' => '6aaef6351746d2af4006249e90711716',
	'src/public/dist/admin.css' => '171a52746ca0ae79e591dd7535306dc5',
	'src/public/dist/widget.css' => '377c0c35808fa21b4062c4b5a2b21a56',
	'src/public/dev/admin.js' => 'a3c56aff525f365d433c511321ac4ed5',
	'src/public/dev/i18n-dir/admin.js' => 'a3c56aff525f365d433c511321ac4ed5',
	'src/public/dev/i18n-dir/interfaces.js' => '07ae337facac44329d3d4cbc194eb811',
	'src/public/dev/i18n-dir/widget.js' => '5b95881bc2203c8dcc6b88d202a9e960',
	'src/public/dev/interfaces.js' => '07ae337facac44329d3d4cbc194eb811',
	'src/public/dev/vendor-admin.js' => '3ddd2f095319447d2945ec86ebf5d25e',
	'src/public/dev/vendor-widget.js' => '35233a7a0ca422d078eb2112830ae2a7',
	'src/public/dev/widget.js' => '5b95881bc2203c8dcc6b88d202a9e960',
	'src/public/dev/admin.css' => '4506913d5cbaf75479c87d6731d6becb',
	'src/public/dev/widget.css' => '377c0c35808fa21b4062c4b5a2b21a56',
);
