<?php
/* This file was automatically generated by the `grunt libs:cachebuster` command (Thu May 26 2022 22:28:12 GMT+0200 (Central European Summer Time)). */
return array(
	'mobx' => '4.15.4',
	'react' => '17.0.2',
	'react-dom' => '16.13.1'
);
